#!/usr/bin/env bash
# Codex / "AGENTS.md" adapter: single concatenated file at repo root.
set -euo pipefail

project="$1"
src_global="$2"
src_template="$3"

main="$project/AGENTS.md"
{
    printf "<!-- orkestra:generated source=instructions/global/*+template/* adapter=codex -->\n"
    printf "# AGENTS.md\n\n"
    printf "Generated by Orkestra. Edit sources in \`~/.orkestra/\` then run\n"
    printf "\`orkestra render\`.\n\n"
    while IFS= read -r f; do
        [[ -z "$f" ]] && continue
        printf -- "---\n\n"
        cat "$f"
        printf "\n"
    done < <(find "$src_global" -maxdepth 1 -type f -name "*.md" | sort)
    if [[ -d "$src_template" ]]; then
        while IFS= read -r f; do
            [[ -z "$f" ]] && continue
            printf -- "---\n\n"
            cat "$f"
            printf "\n"
        done < <(find "$src_template" -maxdepth 1 -type f -name "*.md" | sort)
    fi
} > "$main"
