#!/usr/bin/env bash
# Copilot adapter:
#   .github/copilot-instructions.md         <- concatenation of all globals
#   .github/instructions/<name>.md          <- one file per template instruction
set -euo pipefail

project="$1"
src_global="$2"
src_template="$3"

mkdir -p "$project/.github/instructions"

main="$project/.github/copilot-instructions.md"
{
    printf "<!-- orkestra:generated source=instructions/global/* adapter=copilot -->\n"
    printf "# Copilot instructions\n\n"
    printf "These instructions were generated by Orkestra. Do not edit by hand —\n"
    printf "edit the sources under \`~/.orkestra/instructions/global/\` and run\n"
    printf "\`orkestra render\`.\n\n"
    while IFS= read -r f; do
        [[ -z "$f" ]] && continue
        printf -- "---\n\n"
        cat "$f"
        printf "\n"
    done < <(find "$src_global" -maxdepth 1 -type f -name "*.md" | sort)
} > "$main"

if [[ -d "$src_template" ]]; then
    while IFS= read -r f; do
        [[ -z "$f" ]] && continue
        name="$(basename "$f")"
        dst="$project/.github/instructions/$name"
        {
            printf "<!-- orkestra:generated source=template/%s adapter=copilot -->\n" "$name"
            cat "$f"
        } > "$dst"
    done < <(find "$src_template" -maxdepth 1 -type f -name "*.md")
fi
